### ISSUE TITLE
LBL_ACTION_ERROR

### ISSUE THREAD

**Issue by boydthomson** [motaviegas/SuiteCRM_Script#1]
I get an error stating "LBL_ACTION_ERROR" when I click Proceed on the http://<IP_ADDRESS>/#/install page.

I've gone through all the file permissions and log files and can't figure out what is causing the error.

**Comment by motaviegas** [comment]
Sorry for the delay. Do you still have this issue? Have you solved it? If not send a print screen for better understanding. 
Thnkx and again, sorry
